# DON'T EDIT VERSION MANUALLY! THE VERSION VALUES SHOULD BE CHANGED BY
# bump_version.py THE bump_version.py SCRIPT IS LOCATED IN THE PROJECT ROOT
# DIRECTORY. IT UPDATES THE VERSION OF THE PACKAGE AND CREATES A GIT TAG.
VERSION = (0, 1, 0)
__version__ = '.'.join([str(x) for x in VERSION])
