# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    tags:
      - "*.*.*"

jobs:
  deploy:
    runs-on: ${{ matrix.cfg.os }}
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        cfg:
        - {os: windows-latest, python-version: 3.11, architecture: x64}
        - {os: windows-latest, python-version: 3.11, architecture: x86}
        - {os: ubuntu-latest, python-version: 3.11, architecture: x64}
        - {os: macos-latest, python-version: 3.11, architecture: x64}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.cfg.python-version }} ${{ matrix.cfg.architecture }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.cfg.python-version }}
        architecture: ${{ matrix.cfg.architecture }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine build

    - name: Setup
      run: |
        python -m build


    # https://twine.readthedocs.io/en/latest/index.html#environment-variables
    - name: Publish to PyPi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python -m twine upload dist/*

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
